#!/usr/bin/env node
/**
 * Generates src/lib/abis.ts from the Foundry build artifacts.
 *
 * The frontend must never carry a hand-transcribed ABI: a single wrong type
 * or a stale signature encodes calldata that silently means something else.
 * Run `forge build` in contracts/, then run this.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Only what the browser actually calls. Every entry here ships to the client,
// so add a contract when a component needs it, not before.
const CONTRACTS = [{ name: "Safex", export: "safexAbi" }];

const parts = CONTRACTS.map(({ name, export: exportName }) => {
  const artifact = resolve(root, `contracts/out/${name}.sol/${name}.json`);
  if (!existsSync(artifact)) {
    console.error(`missing ${artifact}\nRun: cd contracts && forge build`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
  return `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
});

const header = `// Generated by scripts/sync-abis.mjs from the Foundry build output.
// Do not edit by hand: run \`cd contracts && forge build && node scripts/sync-abis.mjs\`.

`;

const out = resolve(root, "src/lib/abis.ts");
writeFileSync(out, header + parts.join("\n"));
console.log(`wrote ${out} (${CONTRACTS.map((c) => c.name).join(", ")})`);
